//Action types
export const SET_ERROR = 'SET_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_ALL_STORIES = 'SET_ALL_STORIES';
export const SET_SAMPLE_STORIES = 'SET_SAMPLE_STORIES';
export const SET_MY_STORIES = 'SET_MY_STORIES';
export const SET_MY_SEGMENTS = 'SET_MY_SEGMENTS';
export const SET_CURRENT_STORY = 'SET_CURRENT_STORY';
